version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle_lint_test:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      project:
        type: string
      bundler_version:
        type: string
        default: '2.0.1'
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
    steps:
      - samvera/cached_checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install ghostscript ufraw-batch libpng-dev imagemagick ffmpeg libreoffice
      - run:
          name: Install Kakadu
          command: |
            if [ ! -d "kakadu" ]; then
              mkdir ~/downloads
              wget http://kakadusoftware.com/wp-content/uploads/2014/06/KDU77_Demo_Apps_for_Linux-x86-64_150710.zip -O ~/downloads/kakadu.zip
              unzip ~/downloads/kakadu.zip
              mv KDU77_Demo_Apps_for_Linux-x86-64_150710 kakadu
            fi
            sudo cp kakadu/*.so /usr/lib
            sudo cp kakadu/* /usr/bin

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: << parameters.project >>

      - samvera/install_solr_core

      - samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_lint_test:
          ruby_version: "2.4.5"
          name: "ruby2-4-5"
          project: 'hydra-derivatives'
      - bundle_lint_test:
          ruby_version: "2.5.5"
          name: "ruby2-5-5"
          project: 'hydra-derivatives'
      - bundle_lint_test:
          ruby_version: "2.6.2"
          name: "ruby2-6-2"
          project: 'hydra-derivatives'
