version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0
jobs:
  bundle_lint_test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.1.4
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
      solr_version: 7-slim
    steps:
      - samvera/cached_checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install ghostscript libpng-dev imagemagick ffmpeg libreoffice
      - setup_remote_docker
      - run:
          name: Install Kakadu
          command: |
            docker create --name kakadu josejuansanchez/kakadu:1.0
            docker cp kakadu:/kakadu kakadu
            sudo cp kakadu/*.so /usr/lib
            sudo cp kakadu/* /usr/bin
      - run:
          name: Modify ImageMagick security policy
          command: sudo sed -i 's/policy domain="coder" rights="none" pattern="PDF"/policy domain="coder" rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml

      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>

      - samvera/install_solr_core

      - samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_lint_test:
          name: ruby2-4
          ruby_version: 2.4.10
      - bundle_lint_test:
          name: ruby2-5
          ruby_version: 2.5.9
      - bundle_lint_test:
          name: ruby2-6
          ruby_version: 2.6.9
      - bundle_lint_test:
          name: ruby2-7
          ruby_version: 2.7.5
